use crate::config::AppConfig;
use derive_more::{Display, Error};
use log::info;
use sqlx::postgres::PgPoolOptions;
use sqlx::{Pool, Postgres};

/// `AppDB` represents for the database in use.
#[derive(Clone)]
pub enum AppDB {
    /// Connect to a postgresql database.
    Postgres(Pool<Postgres>), // Or any other database you use.
    /// Manually return data.
    Mock,
}

impl AppDB {
    /// Generates a database connection to postgresql
    pub async fn postgres(config: &AppConfig) -> std::io::Result<Self> {
        let db_url = format!(
            "postgres://{}:{}@{}/{}",
            config.db_user, config.db_password, config.db_host, config.db_database
        );

        let pool_result = PgPoolOptions::new()
            .max_connections(4)
            .connect(&db_url)
            .await;

        if let Ok(pool) = pool_result {
            info!(
                "connected to database {} at {}",
                config.db_database, config.db_host
            );
            Ok(Self::Postgres(pool))
        } else {
            let msg = format!("failed to connect to database, config {:?}", config);
            Err(std::io::Error::other(msg))
        }
    }

    /// Does not connect to any database.
    ///
    /// Any data is generated by hand.
    pub fn mock() -> Self {
        Self::Mock
    }
}

// Example implementation to a database operation.
impl AppDB {
    /// Tests whether the connection is successful.
    pub async fn test_db(&self) -> DBResult<()> {
        match self {
            Self::Postgres(pool) => {
                let row: (i64,) = sqlx::query_as("SELECT $1")
                    .bind(150_i64)
                    .fetch_one(pool)
                    .await?;

                assert_eq!(row.0, 150);
                Ok(())
            }
            // Does not implement for `Mock`
            _ => Err(DBError::Unimplemented),
        }
    }
}

/// `DBResult` is used in database operation methods.
pub type DBResult<T> = std::result::Result<T, DBError>;

/// `DBError` represents for all the possible errors that may occur in a database operation.
#[derive(Debug, Error, Display)]
pub enum DBError {
    SqlxError(sqlx::Error),
    Unimplemented,
}

impl From<sqlx::Error> for DBError {
    fn from(err: sqlx::Error) -> Self {
        Self::SqlxError(err)
    }
}
